version: 2

before:
  hooks:
    - go mod download

# 通用的 ldflags
env:
  GLOBAL_LDFLAGS: >-
    -X github.com/zkMeLabs/mechain-relayer/version.AppVersion={{.Version}}
    -X github.com/zkMeLabs/mechain-relayer/version.GitCommit={{.Commit}}
    -X github.com/zkMeLabs/mechain-relayer/version.GitCommitDate={{.Date}}

builds:
  - id: "mechain-relayer-darwin-amd64"
    main: ./main.go
    binary: bin/mechain-relayer
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    ldflags:
      - "{{ .Env.GLOBAL_LDFLAGS }}"

  - id: "mechain-relayer-darwin-arm64"
    main: ./main.go
    binary: bin/mechain-relayer
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CXX=oa64-clang++
    ldflags:
      - "{{ .Env.GLOBAL_LDFLAGS }}"

  - id: "mechain-relayer-linux-amd64"
    main: ./main.go
    binary: bin/mechain-relayer
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=gcc
      - CXX=g++
    ldflags:
      - "{{ .Env.GLOBAL_LDFLAGS }}"

  - id: "mechain-relayer-linux-arm64"
    main: ./main.go
    binary: bin/mechain-relayer
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    ldflags:
      - "{{ .Env.GLOBAL_LDFLAGS }}"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

checksum:
  name_template: "checksums.txt"

release:
  replace_existing_artifacts: true
