
services:
  init:
    container_name: init-relayer
    image: "zkmelabs/mechain-relayer"
    volumes:
      - "./deployment/dockerup:/workspace/deployment/dockerup:Z"
      - "local-env:/workspace/deployment/dockerup/.local"
    working_dir: "/workspace/deployment/dockerup"
    command: >
      bash -c "
      rm -f init_done &&
      bash localup.sh config 4 && 
      touch init_done && 
      sleep infinity
      "
    healthcheck:
      test: ["CMD-SHELL", "test -f /workspace/deployment/dockerup/init_done && echo 'OK' || exit 1"]
      interval: 10s
      retries: 5
    restart: "on-failure"
  rnode0:
    container_name: mechain-relayer-0
    depends_on:
      init:
        condition: service_healthy
    image: "zkmelabs/mechain-relayer"
    volumes:
      - "local-env:/app"
    command: >
      greenfield-relayer run --config-type local --config-path /app/relayer0/config.json --log_dir json
  rnode1:
    container_name: mechain-relayer-1
    depends_on:
      init:
        condition: service_healthy
    image: "zkmelabs/mechain-relayer"
    volumes:
      - "local-env:/app"
    command: >
      greenfield-relayer run --config-type local --config-path /app/relayer1/config.json --log_dir json
  rnode2:
    container_name: mechain-relayer-2
    depends_on:
      init:
        condition: service_healthy
    image: "zkmelabs/mechain-relayer"
    volumes:
      - "local-env:/app"
    command: >
      greenfield-relayer run --config-type local --config-path /app/relayer2/config.json --log_dir json
  rnode3:
    container_name: mechain-relayer-3
    depends_on:
      init:
        condition: service_healthy
    image: "zkmelabs/mechain-relayer"
    volumes:
      - "local-env:/app"
    command: >
      greenfield-relayer run --config-type local --config-path /app/relayer3/config.json --log_dir json
